namespace SealedKeyword
{
	internal class Program
	{
		static void Main(string[] args)
		{
			//SEALED KEYWORDÜ NEDİR ?
			/* BİR SINIFIN MİRAS VERMESİNİ YAHUT BİR BAŞKA DEYİŞLE BAŞKA BİR SINIF TARAFINDAN MİRAS ALINMASINI ENGELLEYEN BİR KEYWORD'DÜR. */

			//SEALED KEYWORD'Ü KULLANIMI DAHA ÇOK PROJENİN GELİŞTİRME SÜRECİNDE TANIMLANIP TANIMLANMAYACAĞINA GÖRE DEĞİŞİR.

			//PERFORMANS ARTIŞI:SEALED KEYWORD'Ü NORMAL BİR SEALED KULLANILMADAN CLASS'A GÖRE DAHA HIZLI BİR ŞEKİLDE DERLEYİCİ DERLEMEKTEDİR.
			//NEDENİ İSE DERLEYİCİNİN BU CLASS'IN BAŞKA BİR CLASS'TAN KALITIM ALMAYACAĞINI BİLMESİNDEN DOLAYIDIR.
			
			//CLASS KULLANIMLARINDA EN ALTTAKİ SINIFIN SON SINIF OLDUĞUNU BELİRTMEK İÇİNDE KULLANABİLİRİZ.
			Muhabbet_Kusu kus = new Muhabbet_Kusu();
			kus.Tanit(); //BURADA TANIMLAMIŞ OLDUĞUMUZ X METHODU ARTIK KUS CLASS'INDAKİ X METHODU OLARAK ÇALIŞACAKTIR.NEDENİ İSE KUŞ CLASSINDA TANIMLAMIŞ OLDUĞUMUZ SEALED KEYWORD'Ü İLE OVERRİDE EDİLME BAĞLANTISINI KESMİŞ OLDUK.
			Console.ReadLine();
		}
	}
}